baseURL: "https://cimpel-blogs.netlify.app/"
languageCode: "en-us"
title: "Cimpel's Blog"
paginate: 10

theme: stack

DefaultContentLanguage: en

permalinks:
  post: /p/:slug/
  page: /:slug/


params:
  mainSections:
    - posts
  featuredImageField: image
  rssFullContent: true
  favicon: img/favicon.ico

  sidebar:
    emoji: 
    subtitle: The Epic Saga of LSS
    avatar:
      enabled: true
      local: true
      src: img/496707.jpg

  dateFormat:
    published: Jan 02, 2006
    lastUpdated: Jan 02, 2006 15:04 MST

  article:
        math: false
        toc: true
        readingTime: true

  widgets:
    enabled:
      - search
      - archives
      - tag-cloud

    archives:
      limit: 5

    tagCloud:
      limit: 10

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: -100
      params:
        ### For demonstration purpose, the home link will be open in a new tab
        newTab: false
        icon: home

  

related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
    - name: tags
      weight: 100

    - name: categories
      weight: 200

markup:
  goldmark:
    renderer:
      ## Set to true if you have HTML content inside Markdown
      unsafe: false
  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2
  highlight:
    noClasses: false
